-- CREATE DATABASE DB;
USE DB;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    latestLoginAt TIMESTAMP,
    passkeyEnabled BOOLEAN DEFAULT FALSE
);

-- loginMethod: passkey
CREATE TABLE IF NOT EXISTS auth (
    auth_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    auth_uuid VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    loginAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipAddress VARCHAR(255) NOT NULL,
    loginMethod VARCHAR(255) NOT NULL,
    loginDeviceName VARCHAR(255) NOT NULL,
    loginLocation VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS passkey (
    passkey_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    passkey_uid VARCHAR(255) NOT NULL,
    public_key VARCHAR(255) NOT NULL,
    counter INT NOT NULL,
    transports VARCHAR(255),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
    log_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    log_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(255) NOT NULL
);
