-- CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passkeyEnabled BOOLEAN DEFAULT FALSE
);

-- loginMethod: passkey
CREATE TABLE IF NOT EXISTS auth (
    auth_id SERIAL PRIMARY KEY,
    auth_uuid VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    loginAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    loginMethod VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS passkey (
    passkey_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    passkey_uid VARCHAR(255) NOT NULL,
    public_key VARCHAR(255) NOT NULL,
    counter INT NOT NULL,
    transports VARCHAR(255),
    createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS logs (
    log_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    log_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wallet (
    wallet_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    wallet_uuid VARCHAR(255) NOT NULL,
    wallet_address VARCHAR(255) NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- content_type: message, transaction
CREATE TABLE IF NOT EXISTS signrequest (
    signrequest_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    signrequest_uuid VARCHAR(255) NOT NULL,
    request_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_type VARCHAR(255) NOT NULL,
    request_status VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
