CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passkeyEnabled BOOLEAN DEFAULT FALSE
);

-- loginMethod: passkey
CREATE TABLE IF NOT EXISTS auth (
    auth_id SERIAL PRIMARY KEY,
    auth_uuid VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    loginAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipAddress VARCHAR(255) NOT NULL,
    loginMethod VARCHAR(255) NOT NULL,
    loginDeviceName VARCHAR(255) NOT NULL,
    loginLocation VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS passkey (
    passkey_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    passkey_uid VARCHAR(255) NOT NULL,
    public_key VARCHAR(255) NOT NULL,
    counter INT NOT NULL,
    transports VARCHAR(255),
    createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS logs (
    log_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    log_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
