version: "3"
services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@skyproton.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    build: .
    # image: ghcr.io/david200308/central-custody-blockchain-wallet-platform/backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(\"wallet.api.skyproton.com\")"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    # ports:
    #   - "3001:3001"
    environment:
      - DB_URL_FILE=/run/secrets/walletplatform_db_url
      - JWT_PRIVATE_KEY_FILE=/run/secrets/walletplatform_jwt_private_key
      - JWT_PUBLIC_KEY_FILE=/run/secrets/walletplatform_jwt_public_key
      - DOCS_USER_FILE=/run/secrets/walletplatform_docs_user
      - DOCS_PASSWORD_FILE=/run/secrets/walletplatform_docs_password
      - PASSKEY_RPNAME_FILE=/run/secrets/walletplatform_passkey_rpname
      - PASSKEY_RPID_FILE=/run/secrets/walletplatform_passkey_rpid
      - PASSKEY_ORIGIN_FILE=/run/secrets/walletplatform_passkey_origin
      - AES_KEY_FILE=/run/secrets/walletplatform_aes_key
      - SENTRY_DSN_FILE=/run/secrets/walletplatform_sentry_dsn
      - REDIS_URL=redis://redis:6380
    secrets:
      - walletplatform_db_url
      - walletplatform_jwt_private_key
      - walletplatform_jwt_public_key
      - walletplatform_docs_user
      - walletplatform_docs_password
      - walletplatform_passkey_rpname
      - walletplatform_passkey_rpid
      - walletplatform_passkey_origin
      - walletplatform_aes_key
      - walletplatform_sentry_dsn
    deploy:
      # mode: replicated
      # replicas: 3
      update_config:
        order: start-first
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes: 
  letsencrypt:
    driver: local
  redis:
    driver: local

secrets:
  walletplatform_db_url:
    external: true
  walletplatform_jwt_private_key:
    external: true
  walletplatform_jwt_public_key:
    external: true
  walletplatform_docs_user:
    external: true
  walletplatform_docs_password:
    external: true
  walletplatform_passkey_rpname:
    external: true
  walletplatform_passkey_rpid:
    external: true
  walletplatform_passkey_origin:
    external: true
  walletplatform_aes_key:
    external: true
  walletplatform_sentry_dsn:
    external: true
