name: pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - "Backend/**"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Check for changes in Backend directory
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- Backend; then
            echo "No changes in Backend directory."
            echo "should_run=false" >> $GITHUB_ENV
          else
            echo "Changes detected in Backend directory."
            echo "should_run=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set up Google Cloud SDK
        if: env.should_run == 'true'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with Google Artifact Registry
        if: env.should_run == 'true'
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_URL }}
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_ARTIFACT_REGISTRY_URL }}
        shell: bash

      - name: Log in to GitHub Container Registry
        if: env.should_run == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: env.should_run == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: |
            ghcr.io/david200308/central-custody-blockchain-wallet-platform/backend:latest
            ghcr.io/david200308/central-custody-blockchain-wallet-platform/backend:${{ github.sha }}
            ${{ secrets.GCP_ARTIFACT_REGISTRY_DOMAIN }}:latest
            ${{ secrets.GCP_ARTIFACT_REGISTRY_DOMAIN }}:${{ github.sha }}
